// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: analysis_runs.sql

package sqlcgen

import (
	"context"
)

const completeAnalysisRun = `-- name: CompleteAnalysisRun :one
UPDATE analysis_runs
SET status = $2,
    stage = $3,
    finished_at = now(),
    meters_analyzed = $4,
    anomalies_found = $5,
    high_priority = $6
WHERE id = $1
RETURNING id, tenant_id, started_at, finished_at, status, stage, meters_analyzed, anomalies_found, high_priority
`

type CompleteAnalysisRunParams struct {
	ID             int64  `json:"id"`
	Status         string `json:"status"`
	Stage          string `json:"stage"`
	MetersAnalyzed int32  `json:"meters_analyzed"`
	AnomaliesFound int32  `json:"anomalies_found"`
	HighPriority   int32  `json:"high_priority"`
}

func (q *Queries) CompleteAnalysisRun(ctx context.Context, arg CompleteAnalysisRunParams) (AnalysisRun, error) {
	row := q.db.QueryRow(ctx, completeAnalysisRun,
		arg.ID,
		arg.Status,
		arg.Stage,
		arg.MetersAnalyzed,
		arg.AnomaliesFound,
		arg.HighPriority,
	)
	var i AnalysisRun
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Status,
		&i.Stage,
		&i.MetersAnalyzed,
		&i.AnomaliesFound,
		&i.HighPriority,
	)
	return i, err
}

const createAnalysisRun = `-- name: CreateAnalysisRun :one
INSERT INTO analysis_runs (tenant_id, status, stage)
VALUES ($1, 'RUNNING', 'READINGS')
RETURNING id, tenant_id, started_at, finished_at, status, stage, meters_analyzed, anomalies_found, high_priority
`

func (q *Queries) CreateAnalysisRun(ctx context.Context, tenantID int32) (AnalysisRun, error) {
	row := q.db.QueryRow(ctx, createAnalysisRun, tenantID)
	var i AnalysisRun
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Status,
		&i.Stage,
		&i.MetersAnalyzed,
		&i.AnomaliesFound,
		&i.HighPriority,
	)
	return i, err
}

const getAnalysisRun = `-- name: GetAnalysisRun :one
SELECT id, tenant_id, started_at, finished_at, status, stage, meters_analyzed, anomalies_found, high_priority FROM analysis_runs WHERE tenant_id = $1 AND id = $2
`

type GetAnalysisRunParams struct {
	TenantID int32 `json:"tenant_id"`
	ID       int64 `json:"id"`
}

func (q *Queries) GetAnalysisRun(ctx context.Context, arg GetAnalysisRunParams) (AnalysisRun, error) {
	row := q.db.QueryRow(ctx, getAnalysisRun, arg.TenantID, arg.ID)
	var i AnalysisRun
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Status,
		&i.Stage,
		&i.MetersAnalyzed,
		&i.AnomaliesFound,
		&i.HighPriority,
	)
	return i, err
}
