// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: anomalies.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAnomalyByID = `-- name: GetAnomalyByID :one
SELECT id, tenant_id, analysis_run_id, meter_id, detected_at, window_start, window_end, type, severity, confidence, reason, recommended_action, status, baseline_kwh, actual_kwh, variation_pct, evidence FROM anomalies WHERE tenant_id = $1 AND id = $2
`

type GetAnomalyByIDParams struct {
	TenantID int32 `json:"tenant_id"`
	ID       int64 `json:"id"`
}

func (q *Queries) GetAnomalyByID(ctx context.Context, arg GetAnomalyByIDParams) (Anomaly, error) {
	row := q.db.QueryRow(ctx, getAnomalyByID, arg.TenantID, arg.ID)
	var i Anomaly
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AnalysisRunID,
		&i.MeterID,
		&i.DetectedAt,
		&i.WindowStart,
		&i.WindowEnd,
		&i.Type,
		&i.Severity,
		&i.Confidence,
		&i.Reason,
		&i.RecommendedAction,
		&i.Status,
		&i.BaselineKwh,
		&i.ActualKwh,
		&i.VariationPct,
		&i.Evidence,
	)
	return i, err
}

const insertAnomaly = `-- name: InsertAnomaly :one
INSERT INTO anomalies (
    tenant_id, analysis_run_id, meter_id, window_start, window_end,
    type, severity, confidence, reason, recommended_action, status,
    baseline_kwh, actual_kwh, variation_pct, evidence
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, 'OPEN', $11, $12, $13, $14
)
RETURNING id, tenant_id, analysis_run_id, meter_id, detected_at, window_start, window_end, type, severity, confidence, reason, recommended_action, status, baseline_kwh, actual_kwh, variation_pct, evidence
`

type InsertAnomalyParams struct {
	TenantID          int32              `json:"tenant_id"`
	AnalysisRunID     int64              `json:"analysis_run_id"`
	MeterID           string             `json:"meter_id"`
	WindowStart       pgtype.Timestamptz `json:"window_start"`
	WindowEnd         pgtype.Timestamptz `json:"window_end"`
	Type              string             `json:"type"`
	Severity          string             `json:"severity"`
	Confidence        float64            `json:"confidence"`
	Reason            string             `json:"reason"`
	RecommendedAction string             `json:"recommended_action"`
	BaselineKwh       float64            `json:"baseline_kwh"`
	ActualKwh         float64            `json:"actual_kwh"`
	VariationPct      float64            `json:"variation_pct"`
	Evidence          []byte             `json:"evidence"`
}

func (q *Queries) InsertAnomaly(ctx context.Context, arg InsertAnomalyParams) (Anomaly, error) {
	row := q.db.QueryRow(ctx, insertAnomaly,
		arg.TenantID,
		arg.AnalysisRunID,
		arg.MeterID,
		arg.WindowStart,
		arg.WindowEnd,
		arg.Type,
		arg.Severity,
		arg.Confidence,
		arg.Reason,
		arg.RecommendedAction,
		arg.BaselineKwh,
		arg.ActualKwh,
		arg.VariationPct,
		arg.Evidence,
	)
	var i Anomaly
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AnalysisRunID,
		&i.MeterID,
		&i.DetectedAt,
		&i.WindowStart,
		&i.WindowEnd,
		&i.Type,
		&i.Severity,
		&i.Confidence,
		&i.Reason,
		&i.RecommendedAction,
		&i.Status,
		&i.BaselineKwh,
		&i.ActualKwh,
		&i.VariationPct,
		&i.Evidence,
	)
	return i, err
}

const listAnomaliesForLatestRun = `-- name: ListAnomaliesForLatestRun :many
SELECT a.id, a.tenant_id, a.analysis_run_id, a.meter_id, a.detected_at, a.window_start, a.window_end, a.type, a.severity, a.confidence, a.reason, a.recommended_action, a.status, a.baseline_kwh, a.actual_kwh, a.variation_pct, a.evidence FROM anomalies a
WHERE a.tenant_id = $1
  AND a.analysis_run_id = (
      SELECT id FROM analysis_runs
      WHERE tenant_id = $1 AND status = 'DONE'
      ORDER BY started_at DESC
      LIMIT 1
  )
ORDER BY CASE a.severity WHEN 'HIGH' THEN 0 WHEN 'MEDIUM' THEN 1 ELSE 2 END, a.confidence DESC
`

func (q *Queries) ListAnomaliesForLatestRun(ctx context.Context, tenantID int32) ([]Anomaly, error) {
	rows, err := q.db.Query(ctx, listAnomaliesForLatestRun, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Anomaly
	for rows.Next() {
		var i Anomaly
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.AnalysisRunID,
			&i.MeterID,
			&i.DetectedAt,
			&i.WindowStart,
			&i.WindowEnd,
			&i.Type,
			&i.Severity,
			&i.Confidence,
			&i.Reason,
			&i.RecommendedAction,
			&i.Status,
			&i.BaselineKwh,
			&i.ActualKwh,
			&i.VariationPct,
			&i.Evidence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAnomalyStatus = `-- name: UpdateAnomalyStatus :one
UPDATE anomalies SET status = $3
WHERE tenant_id = $1 AND id = $2
RETURNING id, tenant_id, analysis_run_id, meter_id, detected_at, window_start, window_end, type, severity, confidence, reason, recommended_action, status, baseline_kwh, actual_kwh, variation_pct, evidence
`

type UpdateAnomalyStatusParams struct {
	TenantID int32  `json:"tenant_id"`
	ID       int64  `json:"id"`
	Status   string `json:"status"`
}

func (q *Queries) UpdateAnomalyStatus(ctx context.Context, arg UpdateAnomalyStatusParams) (Anomaly, error) {
	row := q.db.QueryRow(ctx, updateAnomalyStatus, arg.TenantID, arg.ID, arg.Status)
	var i Anomaly
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AnalysisRunID,
		&i.MeterID,
		&i.DetectedAt,
		&i.WindowStart,
		&i.WindowEnd,
		&i.Type,
		&i.Severity,
		&i.Confidence,
		&i.Reason,
		&i.RecommendedAction,
		&i.Status,
		&i.BaselineKwh,
		&i.ActualKwh,
		&i.VariationPct,
		&i.Evidence,
	)
	return i, err
}
