// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dashboard.sql

package sqlcgen

import (
	"context"
)

const dashboardAnomalyCounts = `-- name: DashboardAnomalyCounts :one
SELECT
    count(*) AS total,
    count(*) FILTER (WHERE severity = 'HIGH') AS high_priority
FROM anomalies
WHERE tenant_id = $1
`

type DashboardAnomalyCountsRow struct {
	Total        int64 `json:"total"`
	HighPriority int64 `json:"high_priority"`
}

func (q *Queries) DashboardAnomalyCounts(ctx context.Context, tenantID int32) (DashboardAnomalyCountsRow, error) {
	row := q.db.QueryRow(ctx, dashboardAnomalyCounts, tenantID)
	var i DashboardAnomalyCountsRow
	err := row.Scan(&i.Total, &i.HighPriority)
	return i, err
}

const dashboardLatestAnalysisRun = `-- name: DashboardLatestAnalysisRun :one
SELECT id, tenant_id, started_at, finished_at, status, stage, meters_analyzed, anomalies_found, high_priority FROM analysis_runs
WHERE tenant_id = $1
ORDER BY started_at DESC
LIMIT 1
`

func (q *Queries) DashboardLatestAnalysisRun(ctx context.Context, tenantID int32) (AnalysisRun, error) {
	row := q.db.QueryRow(ctx, dashboardLatestAnalysisRun, tenantID)
	var i AnalysisRun
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Status,
		&i.Stage,
		&i.MetersAnalyzed,
		&i.AnomaliesFound,
		&i.HighPriority,
	)
	return i, err
}

const dashboardMeterCount = `-- name: DashboardMeterCount :one
SELECT count(*) FROM meters WHERE tenant_id = $1
`

func (q *Queries) DashboardMeterCount(ctx context.Context, tenantID int32) (int64, error) {
	row := q.db.QueryRow(ctx, dashboardMeterCount, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const dashboardTotalConsumption = `-- name: DashboardTotalConsumption :one
SELECT COALESCE(SUM(consumption_kwh), 0)::float8 FROM readings WHERE tenant_id = $1
`

func (q *Queries) DashboardTotalConsumption(ctx context.Context, tenantID int32) (float64, error) {
	row := q.db.QueryRow(ctx, dashboardTotalConsumption, tenantID)
	var column_1 float64
	err := row.Scan(&column_1)
	return column_1, err
}
