// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertEvent = `-- name: InsertEvent :exec
INSERT INTO events (tenant_id, meter_id, timestamp, type, description)
VALUES ($1, $2, $3, $4, $5)
`

type InsertEventParams struct {
	TenantID    int32              `json:"tenant_id"`
	MeterID     string             `json:"meter_id"`
	Timestamp   pgtype.Timestamptz `json:"timestamp"`
	Type        string             `json:"type"`
	Description string             `json:"description"`
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) error {
	_, err := q.db.Exec(ctx, insertEvent,
		arg.TenantID,
		arg.MeterID,
		arg.Timestamp,
		arg.Type,
		arg.Description,
	)
	return err
}

const listEventsByMeter = `-- name: ListEventsByMeter :many
SELECT id, tenant_id, meter_id, timestamp, type, description FROM events
WHERE tenant_id = $1 AND meter_id = $2
ORDER BY timestamp
`

type ListEventsByMeterParams struct {
	TenantID int32  `json:"tenant_id"`
	MeterID  string `json:"meter_id"`
}

func (q *Queries) ListEventsByMeter(ctx context.Context, arg ListEventsByMeterParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEventsByMeter, arg.TenantID, arg.MeterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.MeterID,
			&i.Timestamp,
			&i.Type,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
