// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: meters.sql

package sqlcgen

import (
	"context"
)

const countReadings = `-- name: CountReadings :one
SELECT count(*) FROM readings WHERE tenant_id = $1
`

func (q *Queries) CountReadings(ctx context.Context, tenantID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countReadings, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getMeterByMeterID = `-- name: GetMeterByMeterID :one
SELECT id, tenant_id, meter_id, name, location, status, created_at FROM meters WHERE tenant_id = $1 AND meter_id = $2
`

type GetMeterByMeterIDParams struct {
	TenantID int32  `json:"tenant_id"`
	MeterID  string `json:"meter_id"`
}

func (q *Queries) GetMeterByMeterID(ctx context.Context, arg GetMeterByMeterIDParams) (Meter, error) {
	row := q.db.QueryRow(ctx, getMeterByMeterID, arg.TenantID, arg.MeterID)
	var i Meter
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.MeterID,
		&i.Name,
		&i.Location,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listMeters = `-- name: ListMeters :many
SELECT id, tenant_id, meter_id, name, location, status, created_at FROM meters WHERE tenant_id = $1 ORDER BY meter_id
`

func (q *Queries) ListMeters(ctx context.Context, tenantID int32) ([]Meter, error) {
	rows, err := q.db.Query(ctx, listMeters, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Meter
	for rows.Next() {
		var i Meter
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.MeterID,
			&i.Name,
			&i.Location,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMeter = `-- name: UpsertMeter :one
INSERT INTO meters (tenant_id, meter_id, name, location, status)
VALUES ($1, $2, $3, $4, 'OK')
ON CONFLICT (tenant_id, meter_id) DO UPDATE SET name = EXCLUDED.name
RETURNING id, tenant_id, meter_id, name, location, status, created_at
`

type UpsertMeterParams struct {
	TenantID int32  `json:"tenant_id"`
	MeterID  string `json:"meter_id"`
	Name     string `json:"name"`
	Location string `json:"location"`
}

func (q *Queries) UpsertMeter(ctx context.Context, arg UpsertMeterParams) (Meter, error) {
	row := q.db.QueryRow(ctx, upsertMeter,
		arg.TenantID,
		arg.MeterID,
		arg.Name,
		arg.Location,
	)
	var i Meter
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.MeterID,
		&i.Name,
		&i.Location,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
