// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AnalysisRun struct {
	ID             int64              `json:"id"`
	TenantID       int32              `json:"tenant_id"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	FinishedAt     pgtype.Timestamptz `json:"finished_at"`
	Status         string             `json:"status"`
	Stage          string             `json:"stage"`
	MetersAnalyzed int32              `json:"meters_analyzed"`
	AnomaliesFound int32              `json:"anomalies_found"`
	HighPriority   int32              `json:"high_priority"`
}

type Anomaly struct {
	ID                int64              `json:"id"`
	TenantID          int32              `json:"tenant_id"`
	AnalysisRunID     int64              `json:"analysis_run_id"`
	MeterID           string             `json:"meter_id"`
	DetectedAt        pgtype.Timestamptz `json:"detected_at"`
	WindowStart       pgtype.Timestamptz `json:"window_start"`
	WindowEnd         pgtype.Timestamptz `json:"window_end"`
	Type              string             `json:"type"`
	Severity          string             `json:"severity"`
	Confidence        float64            `json:"confidence"`
	Reason            string             `json:"reason"`
	RecommendedAction string             `json:"recommended_action"`
	Status            string             `json:"status"`
	BaselineKwh       float64            `json:"baseline_kwh"`
	ActualKwh         float64            `json:"actual_kwh"`
	VariationPct      float64            `json:"variation_pct"`
	Evidence          []byte             `json:"evidence"`
}

type Event struct {
	ID          int64              `json:"id"`
	TenantID    int32              `json:"tenant_id"`
	MeterID     string             `json:"meter_id"`
	Timestamp   pgtype.Timestamptz `json:"timestamp"`
	Type        string             `json:"type"`
	Description string             `json:"description"`
}

type Meter struct {
	ID        int32              `json:"id"`
	TenantID  int32              `json:"tenant_id"`
	MeterID   string             `json:"meter_id"`
	Name      string             `json:"name"`
	Location  string             `json:"location"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Reading struct {
	ID             int64              `json:"id"`
	TenantID       int32              `json:"tenant_id"`
	MeterID        string             `json:"meter_id"`
	Timestamp      pgtype.Timestamptz `json:"timestamp"`
	ConsumptionKwh float64            `json:"consumption_kwh"`
	VoltageV       float64            `json:"voltage_v"`
	CurrentA       float64            `json:"current_a"`
	PowerFactor    float64            `json:"power_factor"`
	Status         string             `json:"status"`
}

type Tenant struct {
	ID        int32              `json:"id"`
	Slug      string             `json:"slug"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           int32              `json:"id"`
	TenantID     int32              `json:"tenant_id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Name         string             `json:"name"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
