// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"
)

type Querier interface {
	CompleteAnalysisRun(ctx context.Context, arg CompleteAnalysisRunParams) (AnalysisRun, error)
	CountReadings(ctx context.Context, tenantID int32) (int64, error)
	CreateAnalysisRun(ctx context.Context, tenantID int32) (AnalysisRun, error)
	CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DailyConsumptionAllMeters(ctx context.Context, tenantID int32) ([]DailyConsumptionAllMetersRow, error)
	// Aggregates in Postgres instead of pulling every raw reading to the app
	// to sum client-side - the response stays bounded by day count, not by
	// reading count, no matter how fine-grained the underlying data gets.
	DailyConsumptionByMeter(ctx context.Context, arg DailyConsumptionByMeterParams) ([]DailyConsumptionByMeterRow, error)
	// Scoped to the latest completed run, same as ListAnomaliesForLatestRun -
	// otherwise this grows every time "Run AI Analysis" is clicked instead of
	// reflecting the current state.
	DashboardAnomalyCounts(ctx context.Context, tenantID int32) (DashboardAnomalyCountsRow, error)
	DashboardLatestAnalysisRun(ctx context.Context, tenantID int32) (AnalysisRun, error)
	DashboardMeterCount(ctx context.Context, tenantID int32) (int64, error)
	DashboardTotalConsumption(ctx context.Context, tenantID int32) (float64, error)
	GetAnalysisRun(ctx context.Context, arg GetAnalysisRunParams) (AnalysisRun, error)
	GetAnomalyByID(ctx context.Context, arg GetAnomalyByIDParams) (Anomaly, error)
	GetMeterByMeterID(ctx context.Context, arg GetMeterByMeterIDParams) (Meter, error)
	GetMeterDetail(ctx context.Context, arg GetMeterDetailParams) (GetMeterDetailRow, error)
	GetTenantBySlug(ctx context.Context, slug string) (Tenant, error)
	GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (User, error)
	GetUserByID(ctx context.Context, id int32) (User, error)
	InsertAnomaly(ctx context.Context, arg InsertAnomalyParams) (Anomaly, error)
	InsertEvent(ctx context.Context, arg InsertEventParams) error
	InsertReading(ctx context.Context, arg InsertReadingParams) error
	ListAnomaliesForLatestRun(ctx context.Context, tenantID int32) ([]Anomaly, error)
	ListEventsByMeter(ctx context.Context, arg ListEventsByMeterParams) ([]Event, error)
	ListMeters(ctx context.Context, tenantID int32) ([]Meter, error)
	ListMetersWithConsumption(ctx context.Context, tenantID int32) ([]ListMetersWithConsumptionRow, error)
	ListReadingsByMeter(ctx context.Context, arg ListReadingsByMeterParams) ([]Reading, error)
	// Cursor (keyset) pagination on timestamp: a meter's readings have no
	// upper bound on how many rows they can grow to, so this endpoint must
	// never be able to return an unbounded response.
	ListReadingsByMeterPage(ctx context.Context, arg ListReadingsByMeterPageParams) ([]Reading, error)
	// Used to compute every meter's baseline in one round trip instead of one
	// query per meter (see meters.Handler.List) - still O(readings) in Go,
	// but O(1) in database round trips regardless of meter count.
	ListReadingsByTenant(ctx context.Context, tenantID int32) ([]Reading, error)
	UpdateAnomalyStatus(ctx context.Context, arg UpdateAnomalyStatusParams) (Anomaly, error)
	UpsertMeter(ctx context.Context, arg UpsertMeterParams) (Meter, error)
}

var _ Querier = (*Queries)(nil)
