// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"
)

type Querier interface {
	CountReadings(ctx context.Context, tenantID int32) (int64, error)
	CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetMeterByMeterID(ctx context.Context, arg GetMeterByMeterIDParams) (Meter, error)
	GetTenantBySlug(ctx context.Context, slug string) (Tenant, error)
	GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (User, error)
	GetUserByID(ctx context.Context, id int32) (User, error)
	InsertEvent(ctx context.Context, arg InsertEventParams) error
	InsertReading(ctx context.Context, arg InsertReadingParams) error
	ListEventsByMeter(ctx context.Context, arg ListEventsByMeterParams) ([]Event, error)
	ListMeters(ctx context.Context, tenantID int32) ([]Meter, error)
	ListReadingsByMeter(ctx context.Context, arg ListReadingsByMeterParams) ([]Reading, error)
	UpsertMeter(ctx context.Context, arg UpsertMeterParams) (Meter, error)
}

var _ Querier = (*Queries)(nil)
