// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: readings.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertReading = `-- name: InsertReading :exec
INSERT INTO readings (tenant_id, meter_id, timestamp, consumption_kwh, voltage_v, current_a, power_factor, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (tenant_id, meter_id, timestamp) DO NOTHING
`

type InsertReadingParams struct {
	TenantID       int32              `json:"tenant_id"`
	MeterID        string             `json:"meter_id"`
	Timestamp      pgtype.Timestamptz `json:"timestamp"`
	ConsumptionKwh float64            `json:"consumption_kwh"`
	VoltageV       float64            `json:"voltage_v"`
	CurrentA       float64            `json:"current_a"`
	PowerFactor    float64            `json:"power_factor"`
	Status         string             `json:"status"`
}

func (q *Queries) InsertReading(ctx context.Context, arg InsertReadingParams) error {
	_, err := q.db.Exec(ctx, insertReading,
		arg.TenantID,
		arg.MeterID,
		arg.Timestamp,
		arg.ConsumptionKwh,
		arg.VoltageV,
		arg.CurrentA,
		arg.PowerFactor,
		arg.Status,
	)
	return err
}

const listReadingsByMeter = `-- name: ListReadingsByMeter :many
SELECT id, tenant_id, meter_id, timestamp, consumption_kwh, voltage_v, current_a, power_factor, status FROM readings
WHERE tenant_id = $1 AND meter_id = $2
ORDER BY timestamp
`

type ListReadingsByMeterParams struct {
	TenantID int32  `json:"tenant_id"`
	MeterID  string `json:"meter_id"`
}

func (q *Queries) ListReadingsByMeter(ctx context.Context, arg ListReadingsByMeterParams) ([]Reading, error) {
	rows, err := q.db.Query(ctx, listReadingsByMeter, arg.TenantID, arg.MeterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reading
	for rows.Next() {
		var i Reading
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.MeterID,
			&i.Timestamp,
			&i.ConsumptionKwh,
			&i.VoltageV,
			&i.CurrentA,
			&i.PowerFactor,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
